### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by ghost** [jonathonl/goodform#1]
```
mkdir _build
cd _build
cmake .. -G"MinGW Makefiles"
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/mingw32-make
```

Some C++ header files are not included in source files.For example, `#include <limits>`.

**Comment by jonathonl** [comment]
I added some additional includes and tested with VC14. It could possibly still be missing some include directives when using MinGW. On Windows, you'll need to define NOMINMAX and link ws2_32.lib.
