### ISSUE TITLE
add has memberfunction to form

### ISSUE THREAD

**Issue by xoac** [jonathonl/goodform#10]
Hi,
What do you think about add `bool has(size_t index)` and `bool has(const std::string &key)` member function in `goodform::form`? 

I know there is a possibility to take default if key not exists, but what if you wanna take special action if there is no "field" in variant and still have form in good state (form.is_good()) because filed is optional in form.

I am still using old goodform, but if you agree I can prepare PR (for new version) and maybe change from old version in production.

**Comment by jonathonl** [comment]
Yeah, that seems reasonable.
