### ISSUE TITLE
Long strings cause crash in msgpack

### ISSUE THREAD

**Issue by timrprobocom** [jonathonl/goodform#2]
In msgpack::serialize, in the three sections that handle longer strings (str 8, str 16 and str 32), the code calls v.get&lt;binary&gt;() instead of v.get&lt;std::string&gt;().  That causes a segmentation fault, since the binary member is uninitialized.  This is at lines 188, 198, and 208.

**Comment by jonathonl** [comment]
Thanks for reporting.
